version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/yourdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
